### PR TITLE
Simple tgz release building and publishing

### PR DESCRIPTION
**Pull request by j14159**
@lepoetemaudit does the way the tarball gets laid out match the expectations in your rebar3 work?

### CODE REVIEW

**Comment by lepoetemaudit** [comment]
@j14159 this looks perfect, thanks!

**Comment by lepoetemaudit** [comment]
I just realised it collates the beams from the test profile; is that an issue?

**Comment by j14159** [comment]
Good point - that'll have a lot of extra stuff included.  I'll take a look at making a different profile.

**Comment by j14159** [comment]
OK, now once tests pass travis-ci will compile with the `default` profile and these will get bundled in the release instead.

**Pull request merged**
