### PR TITLE
Remove purge warnings for nicer test output

### PR DESCRIPTION
**Pull request by Licenser**
Purge modules before deleting them during test runs. That turns this

image

into this

image

### CODE REVIEW

**Comment by Licenser** [comment]
The failing tests here is the following code:
```ml
module a
type vHX 'aDiPCKBIIl3Qk_MFBoA_ 'iZ 's3B_ 'k = A | B | C | D | { a : atom , b : atom , fn : atom } | E
type a = F
```

It fails with: `{error,{parse_error,test,1,{syntax_error,"fn"}}}`

I think that is a bug in the generator since `fn` is a reserved word and should not be a key?

**Comment by j14159** [comment]
`fn` recently became a reserved word for lambdas, probably just needs a minor update to the ct suite.

**Comment by Licenser** [comment]
fixed the proper tests too.

**Comment by j14159** [comment]
Fixes #187 

Thanks for this!

**Pull request merged**
