### PR TITLE
Retrying PR with rebase

### LINKED ISSUE #94: Can't refer to a type qualified with a module name
Given

    module m
    type t = int

The following yields a syntax error but should be allowed:

    module n
    type u = m.t

This is especially important since the changes discussed in #62 won't permit `m.t` to be imported but should still allow it to be referenced.

### PR DESCRIPTION
**Pull request by j14159**
FIxes #94

Had some conflicts after rebasing on @danabr and @lepoetemaudit's work so retrying the PR from a clean state.

### CODE REVIEW

**Comment by danabr** [comment]
The commit history looks strange. Did you really do a successful rebase? You should have had way less commits then.

**Comment by j14159** [comment]
There were a number of conflicts since a few of us were in parser and typer at what git thinks is the same time it appears but I did rebase.  Agreed it looks a little messy...suggestions?

**Comment by danabr** [comment]
At this point I would:
git checkout origin/master
git checkout -b fix-92-squashed
git merge --squash fix-92
git commit
git push origin HEAD

That is, squash it all into one commit. You lose some history, but I think the changes are small enough for it to work.

**Comment by j14159** [comment]
That's pretty reasonable.  I think I know what I might've messed up as well so I may try to rewind this somewhere else first.

**Pull request closed without merging**
