### PR TITLE
Support functions as ADT arguments.

### PR DESCRIPTION
**Pull request by danabr**

### CODE REVIEW

**Comment by j14159** [comment]
Thanks for this!

**Comment by danabr** [comment]
Having thought a bit more about this, I think the actual syntax we chose is misleading. In Haskell, OCaml, and Standard ML `int -> bool -> float` means "a function taking an int, and returning another function taking a bool and returning a float". In Alpaca, it means "a function taking an int and a bool, and returning a float".

I think we should pick another syntax to clarify that we actually have multi-arity functions. e.g. `[int,bool] -> float` or `(int, bool) -> float` or similar.

**Comment by lpil** [comment]
I agree. Perhaps open an issue?

**Comment by j14159** [comment]
@danabr makes sense.  The list syntax works for me if you're happy with it.

**Comment by danabr** [comment]
Opened PR #100 to address this.

**Pull request merged**
