### PR TITLE
Add Spanish translation of error messages

### PR DESCRIPTION
**Pull request by yurrriq**
Based on ~~#148~~ ~~#151~~ master.

### CODE REVIEW

**Comment by yurrriq** [comment]
N.B. I'm opening this now so I don't forget. It's based on #148 and I'll rebase as necessary later.

**Comment by j14159** [comment]
@yurrriq I'm excited that this is already a thing :)  Mind rebasing on master?  Will merge right after.

Thanks for this!

**Comment by yurrriq** [comment]
Done!

**Comment by j14159** [comment]
Thanks @yurrriq and @arpunk!  This is great!

**Pull request merged**
